---
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2

multi-ecosystem-groups:
  all-packages:
    schedule:
      interval: weekly
    commit-message:
      prefix: build(deps)

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: all-packages
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: rust-toolchain
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: all-packages
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: cargo
    directories:
      - /
      - tools/cargo-bin/
    patterns: ["*"]
    multi-ecosystem-group: all-packages
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: all-packages
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: all-packages
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
