---
# Gitpod config: https://www.gitpod.io/docs/config-gitpod-file)

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - redhat.vscode-yaml
    - rust-lang.rust-analyzer
    - panicbit.cargo
    - vadimcn.vscode-lldb
    - Swellaby.vscode-rust-test-adapter
    - be5invis.toml
    - serayuzgur.crates
    - esbenp.prettier-vscode
    - jasonnutter.vscode-codeowners
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint

tasks: []
