---
# MegaLinter Config Ref: https://oxsecurity.github.io/megalinter/configuration

# General Settings
SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true

# Linter Enable/Disable
DISABLE:
  - COPYPASTE
  - SPELL
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_TRIVY
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - KUBERNETES_KUBESCAPE
# Tool Specific Config
