---
# MegaLinter Config Ref: https://megalinter.io/latest/configuration

# General Settings
SHOW_ELAPSED_TIME: true

# Linter Enable/Disable
DISABLE_ERRORS: true
DISABLE:
  - COPYPASTE
  - SPELL
# Tool Specific Config
