
rules_rust_dependencies()

# Registers Rust toolchains with the given versions and editions.
rust_register_toolchains(
    versions=["1.83.0"],
    
    # Specifies the Rust edition to use for the registered toolchains
    edition = "2021",
)



load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")


go_rules_dependencies()

go_register_toolchains(version = "1.20.5")

gazelle_dependencies()
