---
# GitHub Actions syntax: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI
"on":
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: read-all
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: oxsecurity/megalinter@v7.13.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload MegaLinter artifacts
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
          retention-days: 1
      - name: Upload MegaLinter scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3.25.15
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: earthly/actions-setup@v1.0.13
        with:
          version: "latest"
      - name: Run build
        run: |
          earthly +all
      - name: Publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          earthly --push --secret CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" --secret CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" +publish
