---
# GitHub Actions Workflows Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Release
"on":
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: read-all
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.semver.outputs.nextStrict }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          branch: ${{ github.event.repository.default_branch }}
          # Config based on https://www.conventionalcommits.org/en/v1.0.0/
          patchList: fix, bugfix, perf, refactor, test, tests, build, chore, ci, docs, style, patch, bug
  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Download latest earthly
        uses: earthly/actions-setup@v1.0.13
        with:
          version: "latest"
      - run: |
          earthly +docs --VERSION="${{ needs.build.outputs.version }}"
      - name: Commit updated metadata files
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: ${{ github.event.repository.default_branch }}
          commit_message: "docs(release): Update metadata files"
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{ needs.build.outputs.version }}
          tag_prefix: "v"
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1.3.0
        with:
          token: ${{ github.token }}
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1.11.0
        with:
          latest-version: ${{ needs.build.outputs.version }}
          release-notes: ${{ steps.changelog.outputs.changes }}
      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: ${{ github.event.repository.default_branch }}
          commit_message: "docs(release): Update CHANGELOG"
          file_pattern: CHANGELOG.md
      - uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changes }}
          tag: v${{ needs.build.outputs.version }}
          name: ${{ needs.build.outputs.version }}
